name: API CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'
    paths:
      - 'api/src/**'
  deployment:
    branches:
      - master
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'

env:
  DEV: c2mvws-dev
  TOOLS: c2mvws-tools
  REPO_NAME: educ-pen-demog-api
  JOB_NAME: master
  APP_NAME: pen-demographics-api
  APP_DOMAIN: pathfinder.gov.bc.ca
  DEV_TAG: dev
  PIPELINE_NAME: pen-demographics-pipeline

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download OC Client
        uses: carlosperate/download-file-action@v1.0.3
        id: download-oc-client
        with:
          file-url: 'https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz'
      - name: Untar OC Client
        run: tar -zxf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz && mv openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit openshift-origin-client
        working-directory: ${{ github.workspace }}
      - name: Add OC Client to path
        run: echo "::add-path::${{github.workspace}}/openshift-origin-client"
      - name: Depoloy to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER_URL }} --token=${{ secrets.OPENSHIFT_API_TOKEN }}
          oc project $TOOLS
          oc delete bc $REPO_NAME-$JOB_NAME --ignore-not-found=true
          oc new-build --name=$REPO_NAME-$JOB_NAME --image-stream=redhat-openjdk18-openshift:1.1 --binary
          oc start-build $REPO_NAME-$JOB_NAME --from-file=./api/target/pendemog-api-0.0.1-SNAPSHOT.jar --wait
          oc project $DEV
          oc tag $TOOLS/$REPO_NAME-$JOB_NAME:latest $REPO_NAME-$JOB_NAME:$DEV_TAG
          oc process -f ./tools/openshift/api.dc.yaml -p REPO_NAME=$REPO_NAME -p JOB_NAME=$JOB_NAME -p NAMESPACE=$DEV -p APP_NAME=$APP_NAME -p HOST_ROUTE=$APP_NAME-$DEV.$APP_DOMAIN -p TAG=$DEV_TAG | oc apply -f -
          oc rollout status dc --watch=true
        working-directory: ${{ github.workspace }}
