name: API CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'
    paths:
      - 'api/src/**'
  deployment:
    branches:
      - master
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'

env:
  DEV: c2mvws-dev
  TOOLS: c2mvws-tools
  REPO_NAME: educ-pen-demog-api
  JOB_NAME: master
  APP_NAME: pen-demographics-api
  APP_DOMAIN: pathfinder.gov.bc.ca
  DEV_TAG: dev
  PIPELINE_NAME: pen-demographics-pipeline

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - run: mvn -f pom.xml -Dmaven.test.skip=true package
      - name: Download OC Client
        uses: carlosperate/download-file-action@v1.0.3
        id: download-oc-client
        with:
          file-url: 'https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz'
          file-name: 'openshift-origin-client.tar.gz'
      - name: Untar OC Client
        run: tar -zxf openshift-origin-client.tar.gz
        working-directory: ${{ github.workspace }}
      - run: ls -la
        working-directory: openshift-origin-client
      - name: Deploy to OpenShift
        run: ./oc version
        working-directory: openshift-origin-client
