name: API Development

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'
    paths:
      - 'api/src/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'api/src/**'
  repository_dispatch:
    types: [test]

env:
  SONAR_PROJECT_KEY: bcgov_EDUC-PEN-DEMOG-API

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Unit Test
        run: mvn -f pom.xml clean test
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Run Sonar Analysis
        run: mvn -f pom.xml sonar:sonar
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=bcgov-sonarcloud
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
        env:
          # Needed to get some information about the pull request, if any. Could be empty
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
